const header3= [
    {  id:1,
       text1:"Save More on App", 
    },
    {   id:2,
        text1:"Sell On Daraz", 
     },
     {  id:3,
        text1:"Help & Support", 
     },
     {  id:4,
        text1:"Login", 
     },
     {  id:5,
        text1:"Sign Up", 
     },
     {  id:6,
        text1:"زبان تبدیل کریں", 
     },
];
export default header3