const flexibel = [
    { id:1,
      list1: "Help Center",
      list2: "About Us",
    },
    { id:2,
      list1: "How to Buy",
      list2: "Digital Payments",
    },
    { id:3,
      list1: "Corporate & Bulk Purchasing",
      list2: "Daraz Donates",
    },
    { id:4,
      list1: "Returns & Refunds",
      list2: "Daraz Blog",
    },
    { id:5,
      list1: "Daraz Shop",
      list2: "Terms & Conditions",
    },
    { id:6,
      list1: "Contact Us",
      list2: "Privacy Policy",
    },
    { id:7,
      list1: "Daraz Pick up Points",
      list2: "Number : 4012118-6",
    },
    { id:8,
      list2: "Number : 1700401211818",
    },
    { id:9,
      list2: "Online Shopping App",
    },
    { id:10,
      list2: "Daraz Exclusive",
    },
    { id:11,
      list2: "Daraz University",
    },
    { id:12,
      list2: "Sell on Daraz",
    },
    { id:13,
      list2: "Join Daraz Affiliate Program",
    },
  ];
  export default flexibel;
  